name: PR CI

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Install cppcheck
      run: |
        sudo apt-get install -y cppcheck

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get install -y build-essential python-dev-is-python3 python3-numpy python3-pytest

    - name: Build library
      run: make PYTHON=python

    - name: Run library tests
      run: make test PYTHON=python

    - name: Copy library to docs/ directory
      run: cp -r permanent/ docs/permanent/

    - name: Build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        build-command: "make html"
        docs-folder: "docs/"

    - name: Fix documentation permissions
      run: |
        chmod -c -R +rX "docs/build/html/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build/html/
